FROM node:14.14.0-alpine

LABEL version="1.0"
LABEL description="This is a docker dev image for the Truvani recommendations front end app"

WORKDIR /app/truvani

COPY package.json .

RUN yarn install

COPY . .

EXPOSE 3000

CMD [ "yarn", "start" ]