const list = [
  {
    Handle: "led-high-tops",
    Title: "",
    "Body (HTML)": "",
    Vendor: "",
    Type: "",
    Tags: "",
    Published: null,
    "Option1 Name": "",
    "Option1 Value": "US 9",
    "Variant Grams": 230,
    "Variant Inventory Tracker": "shopify",
    "Variant Inventory Qty": 4,
    "Variant Inventory Policy": "continue",
    "Variant Fulfillment Service": "manual",
    "Variant Price": 41,
    "Variant Compare At Price": "",
    "Variant Requires Shipping": true,
    "Variant Taxable": true,
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0018/5617/6150/products/woman-outside-brownstone_925x_cbc014a2-b37b-4eda-bd6c-71c0ec7249b3.jpg?v=1545334696",
    "Image Position": null,
    "Image Alt Text": "",
    "Gift Card": null,
    "SEO Title": "",
    "SEO Description": "",
    "Variant Image": "",
    "Variant Weight Unit": "g",
    "Variant Tax Code": "",
    "Cost per item": "",
  },
  {
    Handle: "striped-skirt-and-top",
    Title: "Striped Skirt and Top",
    "Body (HTML)": "Black cotton top with matching striped skirt.",
    Vendor: "Liam Fashions",
    Type: "",
    Tags: "women",
    Published: true,
    "Option1 Name": "Title",
    "Option1 Value": "xs",
    "Variant Grams": 471,
    "Variant Inventory Tracker": "shopify",
    "Variant Inventory Qty": 2,
    "Variant Inventory Policy": "continue",
    "Variant Fulfillment Service": "manual",
    "Variant Price": 57,
    "Variant Compare At Price": "",
    "Variant Requires Shipping": true,
    "Variant Taxable": true,
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0018/5617/6150/products/woman-in-the-city_925x_34c54a7d-e2a0-48fe-a169-fde33a735aef.jpg?v=1545335011",
    "Image Position": 1,
    "Image Alt Text": "woman wearing striped skirt and black tank top",
    "Gift Card": false,
    "SEO Title": "",
    "SEO Description": "",

    "Variant Image": "",
    "Variant Weight Unit": "g",
    "Variant Tax Code": "",
    "Cost per item": "",
  },
  {
    Handle: "striped-skirt",
    Title: "",
    "Body (HTML)": "",
    Vendor: "",
    Type: "",
    Tags: "",
    Published: null,
    "Option1 Name": "",
    "Option1 Value": "xxl",
    "Variant Grams": 310,
    "Variant Inventory Tracker": "shopify",
    "Variant Inventory Qty": 14,
    "Variant Inventory Policy": "continue",
    "Variant Fulfillment Service": "manual",
    "Variant Price": 52,
    "Variant Compare At Price": "",
    "Variant Requires Shipping": true,
    "Variant Taxable": true,
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0018/5617/6150/products/young-hip-woman-at-carnival_925x_710974da-04df-42cc-9917-0b560eca41b7.jpg?v=1545334886",
    "Image Position": null,
    "Image Alt Text": "",
    "Gift Card": null,
    "SEO Title": "",
    "SEO Description": "",
    "Variant Image": "",
    "Variant Weight Unit": "g",
    "Variant Tax Code": "",
    "Cost per item": "",
  },
  {
    Handle: "olive-green-jacket",
    Title: "Olive Green Jacket",
    "Body (HTML)":
      "Loose fitting olive green jacket with buttons and large pockets. Multicoloured pattern on the front of the shoulders.",
    Vendor: "Liam Fashions",
    Type: "",
    Tags: "women",
    Published: true,
    "Option1 Name": "Title",
    "Option1 Value": "xs",
    "Variant Grams": 368,
    "Variant Inventory Tracker": "shopify",
    "Variant Inventory Qty": 0,
    "Variant Inventory Policy": "continue",
    "Variant Fulfillment Service": "manual",
    "Variant Price": 49,
    "Variant Compare At Price": "",
    "Variant Requires Shipping": true,
    "Variant Taxable": true,
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0018/5617/6150/products/urban-fashion_925x_353f971d-ec3e-4218-9437-28cc7cdb0af2.jpg?v=1545334827",
    "Image Position": 1,
    "Image Alt Text": "woman wearing olive green jacket in front of graffiti ",
    "Gift Card": false,
    "SEO Title": "",
    "SEO Description": "",
    "Variant Image": "",
    "Variant Weight Unit": "g",
    "Variant Tax Code": "",
    "Cost per item": "",
  },
];
export default list;
