const FETCH_PRODUCTS_PENDING = "FETCH_PRODUCTS_PENDING";
const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
const FETCH_PRODUCTS_FAILED = "FETCH_PRODUCTS_FAILED";
const FETCH_RECOMMENDATION_FAILED = "FETCH_RECOMMENDATION_FAILED";
const FETCH_RECOMMENDATION_SUCCESS = "FETCH_RECOMMENDATION_SUCCESS";
const FETCH_RECOMMENDATION_PENDING = "FETCH_RECOMMENDATION_PENDING";
const CLEAR_ALL_RECOMMENDATIONS = "CLEAR_ALL_RECOMMENDATIONS";
const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
const REMOVE_RECOMMENDATION = "REMOVE_RECOMMENDATION";
const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";

export {
  FETCH_RECOMMENDATION_FAILED,
  FETCH_RECOMMENDATION_SUCCESS,
  FETCH_RECOMMENDATION_PENDING,
  CLEAR_ALL_RECOMMENDATIONS,
  REMOVE_RECOMMENDATION,
  FETCH_PRODUCTS_FAILED,
  FETCH_PRODUCTS_PENDING,
  FETCH_PRODUCTS_SUCCESS,
  ADD_PRODUCT_TO_CART,
  REMOVE_PRODUCT_FROM_CART,
};
