const FETCH_PRODUCTS_PENDING = "FETCH_PRODUCTS_PENDING";
const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
const FETCH_PRODUCTS_FAILED = "FETCH_PRODUCTS_FAILED";
const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
//const FETCH_RECOMMEND_PENDING = "FETCH_RECOMMEND_PENDING";

export {
  FETCH_PRODUCTS_FAILED,
  FETCH_PRODUCTS_PENDING,
  FETCH_PRODUCTS_SUCCESS,
  ADD_PRODUCT_TO_CART,
  REMOVE_PRODUCT_FROM_CART,
};
