const FETCH_PRODUCTS_PENDING = "FETCH_PRODUCTS_PENDING";
const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
const FETCH_PRODUCTS_FAILED = "FETCH_PRODUCTS_FAILED";
//const FETCH_RECOMMEND_PENDING = "FETCH_RECOMMEND_PENDING";

export {
  FETCH_PRODUCTS_FAILED,
  FETCH_PRODUCTS_PENDING,
  FETCH_PRODUCTS_SUCCESS,
};
